apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: docker.io/mojibakara/numeric-app:~v2
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/githubsecret
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    #repoURL: https://github.com/mojibakara/k8s-devsecops-security-CD.git
    repoURL: git@github.com:mojibakara/k8s-devsecops-security-CD.git
    targetRevision: HEAD
    path: .
    kustomize:
      version: v5.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
