apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: myalias=docker.io/mojibakara/numeric-app
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest
    #argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/githubsecret2
  #  argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    #repoURL: https://github.com/mojibakara/k8s-devsecops-security-CD.git
    repoURL: git@github.com:mojibakara/k8s-devsecops-security-CD.git
    targetRevision: HEAD
    path: .
    kustomize:
      version: v4.5.7
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: true


