apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  strategy: {}
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      serviceAccountName: default
      containers:
      - image: mojibakara/numeric-app:2.3.5.RELEASE-191
        imagePullPolicy: Always      
        name: devsecops-container
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          #readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
spec:
  ports:
  - port: 8686
    protocol: TCP
    targetPort: 8686
    nodePort: 30318
  selector:
    app: devsecops
  type: NodePort